#' cpdetector: Change point estimation in learning curves.
#'
#' The code is adapted from Gallistel et al. (2004).
#' The package consists of a few internal functions and one wrapper function, cp_wrapper.
#'
#' @docType package
#' @name cpdetectorr
#' @import dplyr
NULL

#' Data on rabbit eyeblink conditioning.
#'
#' Data from Gallistel et al. (2004). Original data description: "[Data] are binary, 1 or 0, according
#' as a conditioned blink did or did not occur on a trial. They are discrete-trial data, so the
#' cpd function must be used to find putative change points. They are frequency data, so
#' one might try using the chisquare test. However, these are the kind of data that cause the
#' chisquare test to run into computational difficulties. The random rate test works better
#' with these data."
#'
#' @source \url{http://www.pnas.org/content/suppl/2004/08/31/0404965101.DC1/04965DataSet5.txt/}
"eyeblink"

#' Data on correct choices in a + maze.
#'
#' Data from Gallistel et al. (2004). Original data description: "These are
#' frequencies, so, in principle, a chisquare test is appropriate to test for changes in the
#' expected frequency of correct choice. However, for some frequency data sets, the
#' chisquare test runs into computational difficulties. The chisquare computation is not valid
#' unless the expected number of observations in the cell with the smallest expectations is 5
#' or greater. The function tests for this, and, if this condition is not met, then it uses the
#' Fisher's exact test. However, Fisher's exact test uses factorials, and these can become
#' intractably large. This happens in data where the frequency before a change is already
#' high, say 0.85, and it becomes even higher after the change. Under these conditions, the
#' numbers of observations in the more populous cells become large and the factorials
#' intractable. One can also treat these data as generated by a random rate process that has a
#' certain probability of generating a correct choice on any given trial. In that case, one
#' would use the random rate test. This test is more computationally robust (less likely to
#' run afoul of computational problems) than the chi square test and should be used
#' whenever the chi square test fails for computational reasons."
#'
#' @source \url{http://www.pnas.org/content/suppl/2004/08/31/0404965101.DC1/04965DataSet3.txt/}
"plusmaze"
